import type { Metadata } from "next";
import "../styles/globals.css";
import { ReduxProvider } from "@/redux/provider";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col mt-5">
        <ReduxProvider>
          <Navbar />
          <div className="flex-grow">{children}</div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
